# Generated by Django 6.0 on 2026-01-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
