# Generated by Django 5.2.8 on 2026-01-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_abono_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targeta',
            name='monto_prestado',
        ),
        migrations.AddField(
            model_name='targeta',
            name='monto_base',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targeta',
            name='estado',
            field=models.CharField(choices=[('PAGO', 'Al día'), ('MORA', 'En mora')], default='MORA', max_length=10),
        ),
    ]
