# Generated by Django 5.2.8 on 2026-01-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_targeta_monto_prestado_targeta_monto_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targeta',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
