# Generated by Django 5.2.8 on 2026-01-12 19:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ruta_base_movimientoruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ingresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('egresos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='app.ruta')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('ruta', 'fecha')},
            },
        ),
    ]
