# Generated by Django 5.2.8 on 2026-01-26 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cajaruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajaruta',
            name='creado_en',
        ),
        migrations.AlterField(
            model_name='cajaruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ruta'),
        ),
        migrations.AlterField(
            model_name='cajaruta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoruta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
