# Generated by Django 5.2.8 on 2026-01-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_cajaruta_creado_en_alter_cajaruta_ruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ruta'),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('targeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='app.targeta')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('targeta', 'numero')},
            },
        ),
    ]
