# Generated by Django 5.2.8 on 2026-01-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_abono_cuota_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cuota'),
        ),
    ]
