# Generated by Django 5.2.8 on 2026-02-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20260208_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
