# Generated by Django 6.0 on 2026-03-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cuota_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='saldo_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
