# Generated by Django 6.0 on 2026-04-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cuota_saldo_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='targeta',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targeta',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targeta',
            name='estado',
            field=models.CharField(choices=[('PAGO', 'Al día'), ('MORA', 'En mora'), ('PAGADA', 'Finalizada/Pagada')], default='MORA', max_length=10),
        ),
    ]
