# Generated by Django 6.0 on 2026-04-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_targeta_latitud_targeta_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targeta',
            name='direccion_casa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='targeta',
            name='direccion_negocio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
