# Generated by Django 6.0 on 2026-04-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_targeta_abonos_offset'),
        ('app', '0015_targeta_frecuencia_cobro'),
    ]

    operations = [
    ]
