# Generated by Django 6.0 on 2026-04-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20260411_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targeta',
            name='abonos_offset',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de abonos de ciclos anteriores (renovaciones)', max_digits=12),
        ),
    ]
